import React from 'react';
import { IndianRupee, TrendingUp, Sparkles, PackageCheck } from 'lucide-react';

export default function KPICards({ metrics }) {
  if (!metrics) return null;

  const totalRev = (metrics.total_revenue || 0).toLocaleString('en-IN');
  const aiRev = (metrics.extra_ai_revenue || 0).toLocaleString('en-IN');
  const liftPct = metrics.ai_revenue_lift_percent || 0;
  const convRate = metrics.conversion_rate_percent || 0;
  const deadStock = metrics.dead_stock_units_moved || 0;

  return (
    <div className="merchant-kpi-grid">
      {/* 1. Total Store Revenue */}
      <div className="merchant-kpi-card cyan-kpi">
        <div className="kpi-header">
          <span className="kpi-label">Total Store Revenue</span>
          <div className="kpi-icon-wrap cyan-bg">
            <IndianRupee size={20} />
          </div>
        </div>
        <div className="kpi-main-val">₹{totalRev}</div>
        <div className="kpi-subtext">Total gross sales recorded across store</div>
      </div>

      {/* 2. AI Extra Revenue Lift */}
      <div className="merchant-kpi-card emerald-kpi">
        <div className="kpi-header">
          <span className="kpi-label">AI Extra Revenue Lift</span>
          <div className="kpi-icon-wrap emerald-bg">
            <TrendingUp size={20} />
          </div>
        </div>
        <div className="kpi-main-val emerald-text">
          +₹{aiRev}
          <span className="kpi-badge emerald-badge">+{liftPct}% Lift</span>
        </div>
        <div className="kpi-subtext">Additional revenue generated by DropGenius AI</div>
      </div>

      {/* 3. Agent Conversion Rate */}
      <div className="merchant-kpi-card indigo-kpi">
        <div className="kpi-header">
          <span className="kpi-label">Agent Conversion Rate</span>
          <div className="kpi-icon-wrap indigo-bg">
            <Sparkles size={20} />
          </div>
        </div>
        <div className="kpi-main-val indigo-text">{convRate}%</div>
        <div className="kpi-subtext">Buyer acceptance rate on AI recommendations</div>
      </div>

      {/* 4. Dead Stock Cleared */}
      <div className="merchant-kpi-card amber-kpi">
        <div className="kpi-header">
          <span className="kpi-label">Dead Stock Cleared</span>
          <div className="kpi-icon-wrap amber-bg">
            <PackageCheck size={20} />
          </div>
        </div>
        <div className="kpi-main-val amber-text">{deadStock} <span style={{ fontSize: '1rem', fontWeight: 600 }}>Units</span></div>
        <div className="kpi-subtext">Items moved from wishlist or dead stock cleared</div>
      </div>
    </div>
  );
}
